CREATE TABLE virus (
  virus_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  virus_name TEXT NOT NULL UNIQUE,
  structure TEXT,
  membrane BOOLEAN
);

ALTER TABLE virus
  ADD COLUMN
    family INTEGER REFERENCES classification(family_id)
    ON DELETE SET NULL;
