CREATE TYPE organism AS ENUM (
  'human',
  'vertebrate',
  'invertebrate',
  'plant',
  'fungi',
  'eukaryotic microorganism',
  'bacteria',
  'archaea'
);

CREATE TABLE host (
  host_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  host_type organism NOT NULL,
  host_name TEXT UNIQUE NOT NULL
);
