DROP TABLE IF EXISTS classification;
DROP TABLE IF EXISTS virus;
/*DROP TABLE IF EXISTS host;
DROP TABLE IF EXISTS viral_host;
DROP TABLE IF EXISTS disease_transmission;
DROP TABLE IF EXISTS disease;
DROP TABLE IF EXISTS transmission;*/

--Creates ENUM type for baltimore classification of viruses
DROP TYPE IF EXISTS baltimore;
CREATE TYPE baltimore AS ENUM (
    'I',
    'II',
    'III',
    'IV',
    'V',
    'VI',
    'VII'
);


CREATE TABLE classification(
  family_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  family_name TEXT NOT NULL,
  virus_type baltimore NOT NULL
);

/*CREATE TABLE virus(
  virus_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  virus_name TEXT NOT NULL,
  family INTEGER REFERENCES classification(family_id),
  shape TEXT NOT NULL,
  membrane BOOLEAN NOT NULL,
  facts TEXT NOT NULL
);*/

/*DROP TYPE IF EXISTS organism;
CREATE TYPE organism AS ENUM (
  'animal',
  'plant',
  'human',
  'other'
);

CREATE TABLE host(
  host_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  host_type organism NOT NULL,
  host_name TEXT NOT NULL
  cell_type TEXT
);

CREATE TABLE viral_host(
  virus_id INTEGER REFERENCES virus(virus_id),
  host_id INTEGER REFERENCES host(host_id),
  PRIMARY KEY (virus_id, host_id)
);

CREATE TABLE disease(
  disease_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  disease_name TEXT NOT NULL,
  virus_id INTEGER REFERENCES virus(virus_id),
  symptoms TEXT NOT NULL
);

DROP TYPE IF EXISTS pathway;
CREATE TYPE pathway AS ENUM (
  'direct contact',
  'aerosol',
  'oral',
  'vector',
  'zoonotic',
  'mechanical'
);

CREATE TABLE transmission(
  transmission_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  method pathway NOT NULL,
  animal TEXT
);

CREATE TABLE disease_transmission(
  disease_id INTEGER REFERENCES disease(disease_id),
  transmission_id INTEGER REFERENCES transmission(transmission_id),
  PRIMARY KEY (virus_id, host_id)
);*/
